version: '3.8'
services:
  app:
    container_name: ms-cliente
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: DEFAULT
      MYSQL_URL: mysql:3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      JWT_SECRET: 12345678

  mysql:
    image: mysql:latest
    container_name: mysql-ms
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms-cliente
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql