version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-ms
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql-ms
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
