version: '3.8'
services:
  app:
    container_name: ms-cliente
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: DEFAULT
      POSTGRES_URL: postgresDb:5432
      POSTGRES_USERNAME: user
      POSTGRES_PASSWORD: admin
      JWT_SECRET: 12345678

  postgres:
    image: postgres:latest
    container_name: postgresDb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ms-cliente
      TZ: "America/Fortaleza"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data