spring:
  application:
    name: ms-cliente
  profiles:
    active: "local"
  datasource:
    url: jdbc:mysql://${MYSQL_URL}/ms-cliente
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

api:
  security:
    token:
      expiration-hours: 2
      secret: ${JWT_SECRET}
