spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mysql-ms
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: WARN
    org.springframework.web: INFO