spring:
  application:
    name: ms-cliente
  profiles:
    active: "local"
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}/ms-cliente
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: false

api:
  security:
    token:
      expiration-hours: 2
      secret: ${JWT_SECRET}
server:
  port: 8080
